### ISSUE TITLE
whenever i open questbook the game crashes

### ISSUE THREAD

**Issue by DowntheTracks** [czbuendel/EL2Test#173]
Modpack Version: #### (Latest is not a version number)

If you have Optifine installed, first uninstall it and confirm the issue still occurs if it is repeatable.

**WE DO NOT PROVIDE SUPPORT TO HEAVILY MODIFIED MODPACKS. OUR PACK IS CURATED FOR WORKABILITY AND NO CONTENT OVERLAP, NOT ADDING ADDITIONAL MODS TO.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log Files**
If the pack is crashing please provide the latest.log from the logs folder of your instance. Use https://gist.github.com to create a link to share the log.

**Comment by r3v07v3r** [comment]
Yea, I'm also having this issue.
The server log shows no issue or error, just a client disconnect.


### Modpack Version:
EL2 - 1.17[1.16.5]

### Describe the bug
Fresh install of game, launch and right click to open Quest Book.
Game runs save and exit
Server console shows disconnect.

### To Reproduce
- Fresh install of game
- Launch the game
- Right click to open Quest Book

Screenshots
![image](https://user-images.githubusercontent.com/1626474/189515112-84cbf558-bb7d-40df-91c5-3a3ad7700e23.png)

Log Files
https://gist.github.com/r3v07v3r/9b4af3fa4b3ede4cbb64c2223210f4ea

**Comment by r3v07v3r** [comment]
I believe this is the important part :P
> dev.ftb.mods.ftbquests.client.FTBQuestsClient.openGui(FTBQuestsClient.java:245) ~[?:1605.3.6-build.98] {re:classloading}

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.ftb.mods.ftbquests.client.FTBQuestsClient.openGui(FTBQuestsClient.java:245) ~[?:1605.3.6-build.98] {re:classloading}
	at dev.ftb.mods.ftbquests.item.QuestBookItem.func_77659_a(QuestBookItem.java:35) ~[?:1605.3.6-build.98] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:216) ~[?:?] {re:mixin,xf:fml:placebo:placeboitemusehook,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,re:classloading,xf:fml:placebo:placeboitemusehook,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1391) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1647) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['R3v07v3R'/1558, l='ClientLevel', x=-72.30, y=64.00, z=136.60]]
	Chunk stats: Client Chunk Cache: 1024, 309
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,67,64), Chunk: (at 0,4,0 in -5,4; contains blocks -80,0,64 to -65,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 70299 game time, 70299 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:simplyseasons.mixins.json:client.SSClientWorld,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:sodium.mixins.json:features.world_ticking.MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:APP:assets/mining_dimension/mining_dimension.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.33.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/299161977.call(Unknown Source) [forge-1.16.5-36.2.33.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
```
