### ISSUE TITLE
Game Crash 'java.lang.NullPointerException: Tesselating block model' in version 1.02a

### ISSUE THREAD

**Issue by ratkinsonuk** [czbuendel/EL2Test#71]
It looks like there's an issue with Framed Blocks, which I've logged to the mod author - https://github.com/XFactHD/FramedBlocks/issues/24

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 5/11/21 10:09 AM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
at xfacthd.framedblocks.common.block.IFramedBlock.isSideHidden(IFramedBlock.java:165) ~[?:2.7] {re:mixin,re:classloading}
at xfacthd.framedblocks.common.block.FramedBlock.func_200122_a(FramedBlock.java:87) ~[?:2.7] {re:classloading}
at net.minecraft.block.AbstractBlock$AbstractBlockState.func_200017_a(AbstractBlock.java:529) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:notreepunching.mixins.json:block.AbstractBlockStateAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A}
at net.optifine.util.BlockUtils.shouldSideBeRendered(BlockUtils.java:57) ~[?:?] {re:classloading}
at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:138) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[?:?] {re:classloading}
at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:907) ~[?:?] {re:classloading,xf:OptiFine:default}
at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:734) ~[?:?] {re:classloading,xf:OptiFine:default}
at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:191) ~[?:?] {re:classloading,xf:OptiFine:default}
at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$20261/1197596950.apply(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by ratkinsonuk** [comment]
Please see the update to the issue - you may want to update the pack version to 2.7.2 to be sure

**Comment by czbuendel** [comment]
The pack will be updated, this mod included, once the Supplementaries mod has been updated that has broken surface vegetation generation.
